export const textStyles = {
    userName: {
        fontFamily: 'heading',
        fontWeight: 'medium',
        fontSize: '18px',
        lineHeight: '28px',
    },
    userNickname: {
        fontFamily: 'heading',
        fontWeight: 'normal',
        fontSize: '14px',
        lineHeight: '20px',
        color: 'blackAlpha.700',
    },
    body14: {
        fontFamily: 'heading',
        fontWeight: 'normal',
        fontSize: '14px',
        lineHeight: '20px',
    },
    body16: {
        fontFamily: 'heading',
        fontWeight: 'normal',
        fontSize: '16px',
        lineHeight: '24px',
    },
    body16Muted: {
        fontFamily: 'heading',
        fontWeight: 'normal',
        fontSize: '16px',
        lineHeight: '24px',
        color: 'blackAlpha.600',
    },
    heading20: {
        fontFamily: 'heading',
        fontWeight: 'medium',
        fontSize: '20px',
        lineHeight: '28px',
    },
    heading48: {
        fontFamily: 'heading',
        fontWeight: 'medium',
        fontSize: '48px',
        lineHeight: '48px',
    },
    heading16: {
        fontFamily: 'heading',
        fontWeight: 'medium',
        fontSize: '16px',
        lineHeight: '24px',
    },
    headingBold48: {
        fontFamily: 'heading',
        fontWeight: 'bold',
        fontSize: '48px',
        lineHeight: '48px',
    },
    body12Muted: {
        fontFamily: 'heading',
        fontWeight: 'medium',
        fontSize: '12px',
        lineHeight: '16px',
        color: 'blackAlpha.300',
    },
    body12RegularMuted: {
        fontFamily: 'heading',
        fontWeight: 'normal',
        fontSize: '12px',
        lineHeight: '16px',
        color: 'blackAlpha.600',
    },
    body12SemiBold: {
        fontFamily: 'heading',
        fontWeight: 'semibold',
        fontSize: '12px',
        lineHeight: '16px',
    },
    heading16Bold: {
        fontFamily: 'heading',
        fontWeight: 'bold',
        fontSize: '16px',
        lineHeight: '24px',
    },
    body16SemiBold: {
        fontFamily: 'heading',
        fontWeight: 'semibold',
        fontSize: '16px',
        lineHeight: '24px',
    },
    body12RegularStrong: {
        fontFamily: 'heading',
        fontWeight: 'normal',
        fontSize: '12px',
        lineHeight: '16px',
        color: 'blackAlpha.700',
    },
};
